name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npm test -- -l
      - name: Upload tests report(cypress mochaawesome merged HTML report)
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: reports
